services:
  # Service 1: The migrations
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: crawler_db
    volumes:
      # Persist data so it survives restarts
      - postgres_data:/var/lib/postgresql/data
      # Automatically run our schema script on first startup
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432" # Allows you to connect from your local PC to check data

  # Service 2: Your crawler
  crawler:
    build: .
    depends_on:
      - db # Wait for DB to start before starting crawler
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data: